const mongoose=require("mongoose")

const UserSchema=new mongoose.Schema({
    username:{
        type:String,
        require:true,
        min:3,
        max:30,
        unique:true
    },
    email:{
        type:String,
        required:true,
        unique:true,
    },
    password:{
        type:String,
        required:true,
        min:6
    },
    profilePicture:{
        type:String,
        default:null
    },
    coverPicture:{
        type:String,
        default:""
    },
    followers:{
        type:Array,
        default:[]
    },
    followings:{
        type:Array,
        default:[]
    },
    bookMark:{
        type:Array,
        default:[]
    },
    description:{
        type:String,
        max:60,
        default:""
    },
    city:{
        type:String,
        max:50,
        default:""
    },
    country:{
        type:String,
        max:50,
        default:""
    },
    isAdmin:{
        type:Boolean,
        default:false,
    },
},{timestamps:true});

module.exports=mongoose.model("User",UserSchema);